// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baljebbufdedzfokhqty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhbGplYmJ1ZmRlZHpmb2tocXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjkzNzksImV4cCI6MjA3MTc0NTM3OX0.Bj6O6BSz9OTDG7yMDLRoU_j4OLyBu_1WLRYYpBQlvVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});